language: haskell
env: ZMQVER=3.2.3
before_install: .travis/install-zeromq.sh
script:
  - cabal configure --enable-tests --extra-include-dirs=.travis/zeromq-$ZMQVER/include --extra-lib-dirs=.travis/zeromq-$ZMQVER/src/.libs && cabal build && cabal test